name: waypoine_plugin
version: '1.0-SNAPSHOT'
main: me.richardsm.waypoine_plugin.Waypoine_plugin
api-version: '1.21'
commands:
  setwaypoint:
    description: Set a waypoint at your current location.
  listwaypoints:
    description: List all your waypoints.
    aliases: [lstwp]
  removewaypoint:
    description: Remove a specific waypoint or all waypoints.
    aliases: [rmwp]
  waypoint:
    description: Navigate to a waypoint using your compass.
    aliases: [wp]
  wpcancel:
    description: Cancel current waypoint navigation.
